spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  data:
    redis:
      host: ${spring.data.redis.host}
      port: ${spring.data.redis.port}

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace
  discord:
    webhook-url: ${logging.discord.webhook-url}

jwt:
  secret: ${jwt.secret}
token:
  expire:
    time:
      access: ${token.expire.time.access}

kafka:
  bootstrap-servers: ${kafka.bootstrap-servers}
  sse-notification-topic-name: ${kafka.sse-notification-topic-name}
  sse-notification-group-id: ${kafka.sse-notification-group-id}
  discord-topic-name: ${kafka.discord-topic-name}
  discord-group-id: ${kafka.discord-group-id}