spring:
  profiles:
    active: prod

  data:
    redis:
      host: ${spring.data.redis.host}
      port: ${spring.data.redis.port}

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

jwt:
  secret: ${jwt.secret}
token:
  expire:
    time:
      access: ${token.expire.time.access}

kafka:
  topic-name: ${kafka.topic-name}
  group-id: ${kafka.group-id}
  bootstrap-servers: ${kafka.bootstrap-servers}